[raw_data_layer]
[raw_data_layer.user_information]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/users_information.sql'
query_parameters.last_access_starts_at.name = 'last_access_starts_at'
query_parameters.last_access_starts_at.type = 'TIMESTAMP'
query_parameters.last_access_starts_at.value = '2022-09-24 21:55:00 UTC'
query_parameters.last_access_ends_at.name = 'last_access_ends_at'
query_parameters.last_access_ends_at.type = 'TIMESTAMP'
query_parameters.last_access_ends_at.value = '2022-09-25 6:00:00 UTC'
local_path = 'data/stackoverflow/raw_data_layer/users_information.csv'
table_name = 'users_information'

[raw_data_layer.top_rarest_badges]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/top_rarest_badges.sql'
query_parameters.date_start.name = 'date_start'
query_parameters.date_start.type = 'DATE'
query_parameters.date_start.value = '2013-01-01'
query_parameters.date_end.name = 'date_end'
query_parameters.date_end.type = 'DATE'
query_parameters.date_end.value = '2023-12-31'
query_parameters.min_users_earned.name = 'min_users_earned'
query_parameters.min_users_earned.type = 'INTEGER'
query_parameters.min_users_earned.value = '20'
query_parameters.top_rarest_badges.name = 'top_rarest_badges'
query_parameters.top_rarest_badges.type = 'INTEGER'
query_parameters.top_rarest_badges.value = '100'
local_path = 'data/stackoverflow/raw_data_layer/top_rarest_badges.csv'
table_name = 'top_rarest_badges'

[raw_data_layer.post_answers]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/post_answers.sql'
query_parameters.last_access_starts_at.name = 'last_access_starts_at'
query_parameters.last_access_starts_at.type = 'TIMESTAMP'
query_parameters.last_access_starts_at.value = '2022-09-24 21:55:00 UTC'
query_parameters.last_access_ends_at.name = 'last_access_ends_at'
query_parameters.last_access_ends_at.type = 'TIMESTAMP'
query_parameters.last_access_ends_at.value = '2022-09-25 6:00:00 UTC'
query_parameters.creation_date_start.name = 'creation_date_start'
query_parameters.creation_date_start.type = 'TIMESTAMP'
query_parameters.creation_date_start.value = '2022-05-25 00:00:00 UTC'
query_parameters.creation_date_end.name = 'creation_date_end'
query_parameters.creation_date_end.type = 'TIMESTAMP'
query_parameters.creation_date_end.value = '2022-09-25 00:00:00 UTC'
local_path = 'data/stackoverflow/raw_data_layer/post_answers.csv'
table_name = 'post_answers'

[raw_data_layer.badges_relevant_users]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/badges_relevant_users.sql'
query_parameters.last_access_starts_at.name = 'last_access_starts_at'
query_parameters.last_access_starts_at.type = 'TIMESTAMP'
query_parameters.last_access_starts_at.value = '2022-09-24 21:55:00 UTC'
query_parameters.last_access_ends_at.name = 'last_access_ends_at'
query_parameters.last_access_ends_at.type = 'TIMESTAMP'
query_parameters.last_access_ends_at.value = '2022-09-25 6:00:00 UTC'
query_parameters.hours_interval.name = 'years_interval'
query_parameters.hours_interval.type = 'INTEGER'
query_parameters.hours_interval.value = 10
local_path = 'data/stackoverflow/raw_data_layer/badges_relevant_users.csv'
table_name = 'badges_relevant_users'