[raw_data_layer]
[raw_data_layer.user_information]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/user_information.sql'
table_name = 'users_information'
local_path = 'data/stackoverflow/raw_data_layer/user_information.csv'

[raw_data_layer.badges]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/badges.sql'
table_name = 'badges'
local_path = 'data/stackoverflow/raw_data_layer/badges.csv'