[raw_data_layer]
[raw_data_layer.user_information]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/users.sql'
local_path = 'data/stackoverflow/raw_data_layer/users.csv'
table_name = 'raw_stackoverflow_data_layer.users'

[raw_data_layer.post_answers]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/posts_answers.sql'
local_path = 'data/stackoverflow/raw_data_layer/posts_answers.csv'
table_name = 'raw_stackoverflow_data_layer.posts_answers'

[raw_data_layer.badges]
query_path = 'queries/stackoverflow/data_preparation/raw_data_layer/badges.sql'
local_path = 'data/stackoverflow/raw_data_layer/badges.csv'
table_name = 'raw_stackoverflow_data_layer.badges'